### ISSUE TITLE
Add open source license.

### ISSUE THREAD

**Issue by valentina-s** [orcasound/acoustic-separation#2]
https://choosealicense.com/

In the past GSoC projects have used [MIT](https://choosealicense.com/licenses/mit/) or [BSD](https://opensource.org/licenses/BSD-3-Clause) licenses which are broadly permissive: others can use, modify, republish your code and are common for open source libraries.
@TGAmbra @Devdoot57

**Comment by prafulfillment** [comment]
Fixed by: https://github.com/orcasound/acoustic-separation/commit/a5abb0c98f5b0ebc6d7a7e88a2e4892f61f30374
